# Generated by Django 2.2.16 on 2021-01-21 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20201118_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
            ],
        ),
        migrations.AlterField(
            model_name='todomodel',
            name='duedate',
            field=models.DateTimeField(),
        ),
    ]
