# Generated by Django 2.2.17 on 2021-03-14 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_auto_20210314_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='duedate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='todomodel',
            name='memo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='todomodel',
            name='priority',
            field=models.CharField(blank=True, choices=[('danger', 'high'), ('info', 'normal'), ('success', 'low')], max_length=50, null=True),
        ),
    ]
