# Generated by Django 2.2.17 on 2021-03-19 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_auto_20210314_1151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserve',
            old_name='article',
            new_name='article2',
        ),
        migrations.AddField(
            model_name='reservation',
            name='reserve',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.Reserve'),
        ),
    ]
